title: "My Learning Log"
description: "Daily notes and experiments"
theme: null

remote_theme: tomjoht/documentation-theme-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge